param(
    [string]$ConfigPath = "$PSScriptRoot\..\config\CustomerSettings.json",
    [string]$TemplateIni = "$PSScriptRoot\..\ConfigurationFile.ini",
    [string]$OutputIni = "$PSScriptRoot\..\config\ConfigurationFile.generated.ini",
    [switch]$GenerateIniOnly
)

$ErrorActionPreference = "Stop"

function Read-Settings {
    param([string]$Path)

    if (-not (Test-Path -LiteralPath $Path)) {
        throw "Config file not found: $Path"
    }

    try {
        return Get-Content -LiteralPath $Path -Raw | ConvertFrom-Json
    }
    catch {
        throw "CustomerSettings.json is not valid JSON. Detail: $($_.Exception.Message)"
    }
}

function Ensure-Directory {
    param([string]$Path)

    if ([string]::IsNullOrWhiteSpace($Path)) {
        return
    }

    if (-not (Test-Path -LiteralPath $Path)) {
        New-Item -ItemType Directory -Path $Path -Force | Out-Null
    }
}

function Escape-SqlLiteral {
    param([string]$Value)
    return ($Value -replace "'", "''")
}

function Get-InstanceName {
    param([object]$Settings)

    if ($Settings.InstanceName) {
        return $Settings.InstanceName.ToString()
    }

    return "MSSQLSERVER"
}

function Get-SqlServiceName {
    param([object]$Settings)

    $instanceName = Get-InstanceName -Settings $Settings
    if ($instanceName -eq "MSSQLSERVER") {
        return "MSSQLSERVER"
    }

    return "MSSQL`$$instanceName"
}

function Get-InstanceRegistryId {
    param([object]$Settings)

    $instanceName = Get-InstanceName -Settings $Settings
    $instanceMap = Get-ItemProperty -Path "HKLM:\SOFTWARE\Microsoft\Microsoft SQL Server\Instance Names\SQL" -ErrorAction Stop
    return $instanceMap.$instanceName
}

function Invoke-SqlBatch {
    param(
        [string]$Sql,
        [string]$Database = "master"
    )

    $connectionString = "Server=localhost;Database=$Database;Integrated Security=True;TrustServerCertificate=True;"
    $connection = New-Object System.Data.SqlClient.SqlConnection($connectionString)
    $command = $connection.CreateCommand()
    $command.CommandTimeout = 0
    $command.CommandText = $Sql

    try {
        $connection.Open()
        [void]$command.ExecuteNonQuery()
    }
    finally {
        $connection.Dispose()
    }
}

function Wait-SqlServer {
    $lastError = $null
    for ($i = 1; $i -le 60; $i++) {
        try {
            Invoke-SqlBatch -Sql "SELECT 1;"
            return
        }
        catch {
            $lastError = $_.Exception.Message
            Start-Sleep -Seconds 5
        }
    }

    throw "SQL Server is not ready after waiting. Last error: $lastError"
}

function New-GeneratedIni {
    param(
        [object]$Settings,
        [string]$Path
    )

    foreach ($dir in @(
        $Settings.Paths.DataRoot,
        $Settings.Paths.UserDbData,
        $Settings.Paths.UserDbLog,
        $Settings.Paths.TempDbData,
        $Settings.Paths.TempDbLog,
        $Settings.Paths.Backup
    )) {
        Ensure-Directory -Path $dir
    }

    $securityMode = if ($Settings.AuthenticationMode -eq "Mixed") { "SQL" } else { "Windows" }
    $adminAccounts = ($Settings.SqlAdmins | ForEach-Object { '"{0}"' -f $_ }) -join " "
    $instanceName = Get-InstanceName -Settings $Settings
    if ([string]::IsNullOrWhiteSpace($adminAccounts)) {
        $adminAccounts = '"BUILTIN\Administrators"'
    }

    $ini = @"
; Generated by Setup-SQLServer-2022-Developer.bat
; Source: $ConfigPath

[OPTIONS]
ACTION="Install"
ENU="True"
QUIET="True"
QUIETSIMPLE="False"
UpdateEnabled="False"
USEMICROSOFTUPDATE="False"
FEATURES=SQLENGINE
HELP="False"
INDICATEPROGRESS="False"
INSTANCENAME="$instanceName"
INSTANCEID="$instanceName"
INSTALLSHAREDDIR="C:\Program Files\Microsoft SQL Server"
INSTALLSHAREDWOWDIR="C:\Program Files (x86)\Microsoft SQL Server"
INSTANCEDIR="C:\Program Files\Microsoft SQL Server"
SQLSVCSTARTUPTYPE="Automatic"
AGTSVCSTARTUPTYPE="Automatic"
SQLCOLLATION="SQL_Latin1_General_CP1_CI_AS"
SECURITYMODE="$securityMode"
SAPWD="$($Settings.SaPassword)"
SQLSVCACCOUNT="$($Settings.ServiceAccounts.SqlServiceAccount)"
AGTSVCACCOUNT="$($Settings.ServiceAccounts.AgentServiceAccount)"
SQLSYSADMINACCOUNTS=$adminAccounts
TCPENABLED="$(if ($Settings.Network.EnableTcp) { "1" } else { "0" })"
NPENABLED="$(if ($Settings.Network.EnableNamedPipes) { "1" } else { "0" })"
BROWSERSVCSTARTUPTYPE="Automatic"
SQLTEMPDBFILECOUNT="4"
SQLTEMPDBFILESIZE="64"
SQLTEMPDBFILEGROWTH="64"
SQLTEMPDBLOGFILESIZE="64"
SQLTEMPDBLOGFILEGROWTH="64"
SQLUSERDBDIR="$($Settings.Paths.UserDbData)"
SQLUSERDBLOGDIR="$($Settings.Paths.UserDbLog)"
SQLTEMPDBDIR="$($Settings.Paths.TempDbData)"
SQLTEMPDBLOGDIR="$($Settings.Paths.TempDbLog)"
SQLBACKUPDIR="$($Settings.Paths.Backup)"
"@

    $outputDir = Split-Path -Parent $Path
    Ensure-Directory -Path $outputDir
    Set-Content -LiteralPath $Path -Value $ini -Encoding ASCII
}

function Set-NetworkConfiguration {
    param([object]$Settings)

    $instanceRegistryId = Get-InstanceRegistryId -Settings $Settings
    $tcpRoot = "HKLM:\SOFTWARE\Microsoft\Microsoft SQL Server\$instanceRegistryId\MSSQLServer\SuperSocketNetLib\Tcp"
    $ipAll = Join-Path $tcpRoot "IPAll"

    if (Test-Path -LiteralPath $tcpRoot) {
        Set-ItemProperty -LiteralPath $tcpRoot -Name Enabled -Value ([int][bool]$Settings.Network.EnableTcp)
        Write-Host "[OK] TCP/IP registry flag updated"
    }
    else {
        Write-Host "[SKIP] TCP/IP registry path not found"
    }

    if (Test-Path -LiteralPath $ipAll) {
        Set-ItemProperty -LiteralPath $ipAll -Name TcpDynamicPorts -Value ""
        Set-ItemProperty -LiteralPath $ipAll -Name TcpPort -Value ([string]$Settings.Network.TcpPort)
        Write-Host "[OK] TCP port set to $($Settings.Network.TcpPort)"
    }
    else {
        Write-Host "[SKIP] TCP IPAll registry path not found"
    }

    if ($Settings.Network.OpenFirewall) {
        $ruleName = "SQL Server TCP $($Settings.Network.TcpPort)"
        $rule = Get-NetFirewallRule -DisplayName $ruleName -ErrorAction SilentlyContinue
        if (-not $rule) {
            New-NetFirewallRule -DisplayName $ruleName -Direction Inbound -Action Allow -Protocol TCP -LocalPort ([int]$Settings.Network.TcpPort) | Out-Null
            Write-Host "[OK] Firewall rule created: $ruleName"
        }
        else {
            Write-Host "[SKIP] Firewall rule already exists: $ruleName"
        }
    }

    Restart-Service -Name (Get-SqlServiceName -Settings $Settings) -Force -ErrorAction SilentlyContinue
}

function Apply-ServerSettings {
    param([object]$Settings)

    $memory = [int]$Settings.ServerTuning.MaxServerMemoryMB
    $maxDop = [int]$Settings.ServerTuning.MaxDop
    $cost = [int]$Settings.ServerTuning.CostThresholdForParallelism

    Invoke-SqlBatch -Sql @"
EXEC sys.sp_configure N'show advanced options', 1;
RECONFIGURE;
EXEC sys.sp_configure N'max server memory (MB)', $memory;
RECONFIGURE;
EXEC sys.sp_configure N'max degree of parallelism', $maxDop;
RECONFIGURE;
EXEC sys.sp_configure N'cost threshold for parallelism', $cost;
RECONFIGURE;
"@
    Write-Host "[OK] Server tuning applied"
}

function Apply-DatabaseSettings {
    param([object]$Settings)

    foreach ($db in @($Settings.Databases)) {
        if (-not $db.Name) {
            continue
        }

        $dbName = Escape-SqlLiteral $db.Name
        if ($db.CreateIfMissing) {
            if (Invoke-DbExists -Name $db.Name) {
                Write-Host "[SKIP] Database already exists: $($db.Name)"
            }
            else {
                Invoke-SqlBatch -Sql "CREATE DATABASE [$($db.Name.Replace(']', ']]'))];"
                Write-Host "[OK] Database created: $($db.Name)"
            }
        }

        if ($db.RecoveryModel -and (Invoke-DbExists -Name $db.Name)) {
            $recovery = $db.RecoveryModel.ToString().ToUpperInvariant()
            if ($recovery -in @("FULL", "SIMPLE", "BULK_LOGGED")) {
                Invoke-SqlBatch -Sql "ALTER DATABASE [$($db.Name.Replace(']', ']]'))] SET RECOVERY $recovery;"
                Write-Host "[OK] Recovery model set for $($db.Name): $recovery"
            }
        }
    }
}

function Invoke-DbExists {
    param([string]$Name)

    $connectionString = "Server=localhost;Database=master;Integrated Security=True;TrustServerCertificate=True;"
    $connection = New-Object System.Data.SqlClient.SqlConnection($connectionString)
    $command = $connection.CreateCommand()
    $command.CommandText = "SELECT COUNT(*) FROM sys.databases WHERE name = @name;"
    [void]$command.Parameters.Add("@name", [System.Data.SqlDbType]::NVarChar, 128)
    $command.Parameters["@name"].Value = $Name

    try {
        $connection.Open()
        return ([int]$command.ExecuteScalar()) -gt 0
    }
    finally {
        $connection.Dispose()
    }
}

function Apply-LoginSettings {
    param([object]$Settings)

    foreach ($login in @($Settings.AppLogins)) {
        if (-not $login.LoginName) {
            continue
        }

        $loginName = $login.LoginName.ToString()
        $escapedLogin = $loginName.Replace("]", "]]")

        if ($login.LoginType -eq "WindowsLogin") {
            if (Invoke-LoginExists -Name $loginName) {
                Write-Host "[SKIP] Login already exists: $loginName"
            }
            else {
                Invoke-SqlBatch -Sql @"
IF NOT EXISTS (SELECT 1 FROM sys.server_principals WHERE name = N'$(Escape-SqlLiteral $loginName)')
    CREATE LOGIN [$escapedLogin] FROM WINDOWS;
"@
                Write-Host "[OK] Windows login created: $loginName"
            }
        }
        else {
            $password = Escape-SqlLiteral $login.Password
            $defaultDb = if ($login.DefaultDatabase) { $login.DefaultDatabase.ToString().Replace("]", "]]") } else { "master" }
            if (Invoke-LoginExists -Name $loginName) {
                Write-Host "[SKIP] Login already exists: $loginName"
            }
            else {
                Invoke-SqlBatch -Sql @"
IF NOT EXISTS (SELECT 1 FROM sys.sql_logins WHERE name = N'$(Escape-SqlLiteral $loginName)')
    CREATE LOGIN [$escapedLogin] WITH PASSWORD = N'$password', CHECK_POLICY = OFF, CHECK_EXPIRATION = OFF, DEFAULT_DATABASE = [$defaultDb];
"@
                Write-Host "[OK] SQL login created: $loginName"
            }
        }

        foreach ($role in @($login.ServerRoles)) {
            if ([string]::IsNullOrWhiteSpace($role)) {
                continue
            }

            $roleName = $role.ToString().Replace("]", "]]")
            if (Invoke-ServerRoleMemberExists -RoleName $roleName -LoginName $loginName) {
                Write-Host "[SKIP] Login $loginName already in server role $roleName"
                continue
            }

            Invoke-SqlBatch -Sql @"
IF IS_SRVROLEMEMBER(N'$roleName', N'$(Escape-SqlLiteral $loginName)') = 0
    ALTER SERVER ROLE [$roleName] ADD MEMBER [$escapedLogin];
"@
            Write-Host "[OK] Added login $loginName to server role $roleName"
        }
    }
}

function Invoke-LoginExists {
    param([string]$Name)

    $connectionString = "Server=localhost;Database=master;Integrated Security=True;TrustServerCertificate=True;"
    $connection = New-Object System.Data.SqlClient.SqlConnection($connectionString)
    $command = $connection.CreateCommand()
    $command.CommandText = "SELECT COUNT(*) FROM sys.server_principals WHERE name = @name;"
    [void]$command.Parameters.Add("@name", [System.Data.SqlDbType]::NVarChar, 128)
    $command.Parameters["@name"].Value = $Name

    try {
        $connection.Open()
        return ([int]$command.ExecuteScalar()) -gt 0
    }
    finally {
        $connection.Dispose()
    }
}

function Invoke-ServerRoleMemberExists {
    param(
        [string]$RoleName,
        [string]$LoginName
    )

    $role = Escape-SqlLiteral $RoleName
    $login = Escape-SqlLiteral $LoginName
    $connectionString = "Server=localhost;Database=master;Integrated Security=True;TrustServerCertificate=True;"
    $connection = New-Object System.Data.SqlClient.SqlConnection($connectionString)
    $command = $connection.CreateCommand()
    $command.CommandText = "SELECT ISNULL(IS_SRVROLEMEMBER(N'$role', N'$login'), 0);"

    try {
        $connection.Open()
        return ([int]$command.ExecuteScalar()) -eq 1
    }
    finally {
        $connection.Dispose()
    }
}

$settings = Read-Settings -Path $ConfigPath
New-GeneratedIni -Settings $settings -Path $OutputIni

if ($GenerateIniOnly) {
    Write-Host "[OK] Generated SQL setup config: $OutputIni"
    exit 0
}

Set-NetworkConfiguration -Settings $settings
Wait-SqlServer
Apply-ServerSettings -Settings $settings
Apply-DatabaseSettings -Settings $settings
Apply-LoginSettings -Settings $settings

Write-Host "[OK] SQL network, firewall, tuning, login, and permission settings applied."
